trigger:
  branches:
    exclude: 
    - u/*
pr:
  branches:
    include:
    - master

jobs:
- job: Build
  strategy:
    matrix:
      Win-X64-Release:
        imageName: 'windows-latest'
        _configuration: Release
        _platform: x64
  pool:
    vmImage: $(imageName)
  steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        feedsToUse: 'config'
        nugetConfigPath: 'NuGet.config'
      condition: succeeded()
      displayName: "Restore"
    
    - task: DotNetCoreCLI@2
      inputs:
        command: 'custom'
        custom: 'msbuild'
        arguments: '-property:PlatformTarget=$(_platform)
                    -property:Configuration=$(_configuration)
                    -binaryLogger'
      condition: succeeded()
      displayName: Build

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: 'test'
        nobuild: true
        publishTestResults: true
        arguments: '--collect "Code coverage"
                    --no-build
                    --settings "CodeCoverage.runsettings"'
        projects: '**/*.Test.csproj'
      condition: succeeded()
      env:
        GRANTSETFIXSASTOKEN: $(GRANTSETFIXSASTOKEN)
    
    - task: DotNetCoreCLI@2
      inputs:
        command: 'custom'
        arguments: 'pack'
      displayName: Pack
      condition: succeeded()

    # Should always run
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\artifacts\log\$(_configuration)'
        ArtifactName: '$(_configuration) log folder'
        publishLocation: Container
      continueOnError: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\artifacts\Packages\$(_configuration)\'
        ArtifactName: '$(_configuration) packages folder'
        publishLocation: Container
      displayName: Publish packages folder
      continueOnError: true
      condition: eq(variables['_configuration'], 'Release')
